name: Stress Test Server

on:
  workflow_dispatch  # manual trigger

jobs:
  stress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Start 10 parallel threads, each downloading 5000 times
        run: |
          URL="https://your-server.com/20MB.bin"
          THREADS=10
          REPEATS=5000

          for i in $(seq 1 $THREADS); do
            echo "Thread $i started"
            (
              for j in $(seq 1 $REPEATS); do
                wget -O /dev/null -q "$URL" || echo "Thread $i - Failed at attempt $j"
              done
              echo "Thread $i completed"
            ) &
          done

          wait
          echo "All threads finished"
